### ISSUE TITLE
对于有关文本的建议

### ISSUE THREAD

**Issue by FireEndymion235** [phil616/Teyvatedu#12]
**您好！**
很感谢您为提瓦特教育出版社所做出的重大贡献，也十分感谢您对网站的辛勤付出。
我在测试网站进行总体浏览后，认为网站非常流畅，浏览感到十分舒服，且在电脑与手机上使用皆没有发现技术问题。
**但对于文本问题有下列几项需要反馈：**
1.网站的部分缩写标题为“提教版”，应该为“提教社”。
2.在网页 "https://rpics.cn/contact.html" 中，联系方式一栏内，BiliBili应为“提瓦特教育出版社”，应删去“人民”二字。建议：在QQ联系方式的QQ群聊号中可插入一下超链接 "https://qm.qq.com/q/Jq9rtFOmQO" 。
在该测试网站中，其他方面暂时没有发现问题。
感谢您的理解，希望您能采纳我个人的建议。

**Comment by FireEndymion235** [comment]
![image](https://github.com/phil616/Teyvatedu/assets/111224963/8eef31d8-8c38-41e3-b717-46bc503e7e99)
以上是关于第一点的图片。

**Comment by phil616** [comment]
i've received your advise, related suggestions has been add to the in progress list, we will handle them soon.

**Comment by FireEndymion235** [comment]
再补充：Bilibili联系方式也可插入超链接："https://space.bilibili.com/3546620878654067"
感谢您采纳我的建议。

**Comment by FireEndymion235** [comment]
抱歉，QQ超链接给错了，应该是 "https://qm.qq.com/q/Q6ai2qd6oA" （原来给成编辑群的了）
对不起对不起对不起......

**Comment by phil616** [comment]
latest commit has update the link
