### ISSUE TITLE
关于网站的建议

### ISSUE THREAD

**Issue by huangzhuoyuchina** [phil616/Teyvatedu#15]
网站可以多添加一些备用网址，不然一些地方管的严，无法进入
-----------服务器要部署吗？
-----------网站关于界面中有提到提瓦特教育出版社有著作权，有自主知识产权，可以改掉，不然米哈游可能会送律师函。 
qq：355854330

**Comment by phil616** [comment]
i've received your suggestions, related question will be solved soon.

**Comment by huangzhuoyuchina** [comment]
如何部署到服务器上

**Comment by phil616** [comment]
a docker image can be made with the dockerfile in branch main.
