### ISSUE TITLE
add mutiserver support

### ISSUE THREAD

**Issue by phil616** [phil616/Teyvatedu#16]
add mutiserver support
1. mysql support
2. backups
3. nginx
4. firewall

**Comment by Lourvine** [comment]
mult server support require the outer side system config, one cannot support multapps within the fastapi.
one possible solution is add the cache and one 'DAO' gather them to a docker compose and manage them together.
for example: 
- redis 1 app 1 mysql 1
- redis 2 app 2 mysql 1
etc
and you need an nginx to manage upstreams. the server deploy that nginx is the api server.
