### ISSUE TITLE
添加资源下载站链接

### ISSUE THREAD

**Issue by FireEndymion235** [phil616/Teyvatedu#17]
**您好！**
经社内商议，已开通AList资源下载站："http://d.tsy-s.de/download" 。
之后的电子书等文件下载可以直接挂上资源下载站内的文件下载链接。
您可以在“联系我们”下标明指向该资源下载站的链接。
**感谢您的理解与支持！**

**Comment by phil616** [comment]
your suggest has been add to the next iteration of this project, we will handle your request soon.

**Comment by phil616** [comment]
According to the latest security policy[Security Policy V1.1](https://github.com/phil616/Teyvatedu/blob/main/SECURITY.md), the external links you provided may not all comply with the latest security policy. The developer team is actively looking for solutions. Your problem has been transferred to another issue and added to the next iterative development cycle for detailed discussion. For this issue, it will be closed and archived.
